modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Potion-Studios/All-The-Wood-Weve-Got/issues"
license = "All Rights Reserved"

[[mods]]
modId = "woodwevegot"
version = "${version}"
displayName = "All the Wood We've Got"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
'''
#logoFile = ""

[[dependencies.woodwevegot]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.woodwevegot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
